fix: pin version of chainguard to last working version
newer version requires update to the forked/vendored action in our org namespace

prints:
Status: Downloaded newer image for ghcr.io/wolfi-dev/apko:latest
Error: unknown flag: --package-version-tag-stem
2023/11/03 00:05:35 error during command execution: unknown flag: --package-version-tag-stem